apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: todoapp
  labels:
    app: busybox
spec:
  containers:
  - name: busybox-container
    image: ikulyk404/busyboxplus:curl
    command: ["sh", "-c", "sleep 3600"]
