apiVersion: v1
kind: Pod
metadata:
 name: todoapp-pod
 namespace: todoapp
 labels:
   app: todoapp
spec:
 containers:
 - name: todoapp-pod
   image: nnnikol/todoapp:3.0.0
   ports:
   - containerPort: 8080
   livenessProbe:
      httpGet:
        path: /api/health/live
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5

   readinessProbe:
      httpGet:
        path: /api/health/ready
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5

